# Generated by Django 4.1.3 on 2022-12-07 22:20

import uuid

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partido",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, unique=True, verbose_name="Nome"),
                ),
                (
                    "short_name",
                    models.CharField(max_length=15, unique=True, verbose_name="Sigla"),
                ),
                ("number", models.IntegerField(unique=True, verbose_name="Número")),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "Nenhum"),
                            (1, "Liberal"),
                            (3, "Conservador"),
                            (5, "Social Democrata"),
                            (6, "Socialista"),
                        ],
                        default=0,
                        verbose_name="Espectro",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
