# Generated by Django 4.1.3 on 2022-12-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partidos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partido",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Descrição",
            ),
        ),
    ]
